modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/shizotoaster/thaumon/issues"
license = "MIT"

[[mods]]
modId = "thaumon"
version = "${version}"
displayName = "Thaumon"
authors = "jdlenl, shizotoaster"
credits = "exelerium, unilock, nageih, isengrimus"
description = '''
Thaumcraft-inspired decoration blocks for modern Minecraft
'''
logoFile = "thaumon_logo.png"
displayURL = "https://github.com/shizotoaster/thaumon"
logoBlur = false

[[mixins]]
config = "thaumon-common.mixins.json"
[[mixins]]
config = "thaumon-forge.mixins.json"

[[dependencies.thaumon]]
modId = "neoforge"
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thaumon]]
modId = "minecraft"
versionRange = "1.20.6"
ordering = "NONE"
side = "BOTH"