package jdlenl.thaumon.itemgroup;

import jdlenl.thaumon.block.ThaumonBlocks;
import jdlenl.thaumon.item.ThaumonItems;
import net.minecraft.world.item.CreativeModeTab;

public class ItemGroupUtils {
    public static void addItem(CreativeModeTab.Output entries) {
        entries.accept(ThaumonBlocks.AMBER.get());
        entries.accept(ThaumonBlocks.AMBER_STAIRS.get());
        entries.accept(ThaumonBlocks.AMBER_SLAB.get());
        entries.accept(ThaumonBlocks.AMBER_BRICKS.get());
        entries.accept(ThaumonBlocks.AMBER_BRICK_STAIRS.get());
        entries.accept(ThaumonBlocks.AMBER_BRICK_SLAB.get());
        entries.accept(ThaumonBlocks.AMBERGLASS.get());
        entries.accept(ThaumonBlocks.AMBERGLASS_PANE.get());

        entries.accept(ThaumonBlocks.GREATWOOD_LOG.get());
        entries.accept(ThaumonBlocks.GREATWOOD_WOOD.get());
        entries.accept(ThaumonBlocks.GREATWOOD_LOG_WALL.get());
        entries.accept(ThaumonBlocks.GREATWOOD_LOG_POST.get());
        entries.accept(ThaumonBlocks.GREATWOOD_PLANKS.get());
        entries.accept(ThaumonBlocks.GREATWOOD_STAIRS.get());
        entries.accept(ThaumonBlocks.GREATWOOD_SLAB.get());
        entries.accept(ThaumonBlocks.GREATWOOD_DOOR.get());
        entries.accept(ThaumonBlocks.GREATWOOD_TRAPDOOR.get());
        entries.accept(ThaumonBlocks.GILDED_GREATWOOD_DOOR.get());
        entries.accept(ThaumonBlocks.GILDED_GREATWOOD_TRAPDOOR.get());
        entries.accept(ThaumonBlocks.GREATWOOD_FENCE.get());
        entries.accept(ThaumonBlocks.GREATWOOD_FENCE_GATE.get());
        entries.accept(ThaumonBlocks.GREATWOOD_WINDOW.get());
        entries.accept(ThaumonBlocks.GREATWOOD_WINDOW_PANE.get());
        entries.accept(ThaumonBlocks.EMPTY_GREATWOOD_BOOKSHELF.get());
        entries.accept(ThaumonBlocks.GREATWOOD_BOOKSHELF.get());
        entries.accept(ThaumonBlocks.CLASSIC_GREATWOOD_BOOKSHELF.get());
        entries.accept(ThaumonBlocks.DUSTY_GREATWOOD_BOOKSHELF.get());
        entries.accept(ThaumonBlocks.ALCHEMISTS_GREATWOOD_BOOKSHELF.get());
        entries.accept(ThaumonBlocks.GREATWOOD_GRIMOIRE_BOOKSHELF.get());
        entries.accept(ThaumonBlocks.GREATWOOD_BUTTON.get());
        entries.accept(ThaumonBlocks.GREATWOOD_PRESSURE_PLATE.get());

        entries.accept(ThaumonBlocks.SILVERWOOD_LOG.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_WOOD.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_LOG_WALL.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_LOG_POST.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_PLANKS.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_STAIRS.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_SLAB.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_DOOR.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_TRAPDOOR.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_FENCE.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_FENCE_GATE.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_WINDOW.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_WINDOW_PANE.get());
        entries.accept(ThaumonBlocks.EMPTY_SILVERWOOD_BOOKSHELF.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_BOOKSHELF.get());
        entries.accept(ThaumonBlocks.CLASSIC_SILVERWOOD_BOOKSHELF.get());
        entries.accept(ThaumonBlocks.DUSTY_SILVERWOOD_BOOKSHELF.get());
        entries.accept(ThaumonBlocks.ALCHEMISTS_SILVERWOOD_BOOKSHELF.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_GRIMOIRE_BOOKSHELF.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_BUTTON.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_PRESSURE_PLATE.get());

        entries.accept(ThaumonBlocks.ARCANE_STONE.get());
        entries.accept(ThaumonBlocks.ARCANE_STONE_STAIRS.get());
        entries.accept(ThaumonBlocks.ARCANE_STONE_SLAB.get());
        entries.accept(ThaumonBlocks.ARCANE_STONE_WALL.get());
        entries.accept(ThaumonBlocks.ARCANE_STONE_BRICKS.get());
        entries.accept(ThaumonBlocks.ARCANE_BRICK_STAIRS.get());
        entries.accept(ThaumonBlocks.ARCANE_BRICK_SLAB.get());
        entries.accept(ThaumonBlocks.ARCANE_BRICK_WALL.get());
        entries.accept(ThaumonBlocks.LARGE_ARCANE_STONE_BRICKS.get());
        entries.accept(ThaumonBlocks.LARGE_ARCANE_BRICK_STAIRS.get());
        entries.accept(ThaumonBlocks.LARGE_ARCANE_BRICK_SLAB.get());
        entries.accept(ThaumonBlocks.LARGE_ARCANE_BRICK_WALL.get());
        entries.accept(ThaumonBlocks.ARCANE_STONE_TILES.get());
        entries.accept(ThaumonBlocks.ARCANE_TILE_STAIRS.get());
        entries.accept(ThaumonBlocks.ARCANE_TILE_SLAB.get());
        entries.accept(ThaumonBlocks.ARCANE_STONE_PILLAR.get());
        entries.accept(ThaumonBlocks.RUNIC_ARCANE_STONE.get());
        entries.accept(ThaumonBlocks.RUNIC_ARCANE_TILES.get());
        entries.accept(ThaumonBlocks.TILED_ARCANE_STONE.get());
        entries.accept(ThaumonBlocks.INLAID_ARCANE_STONE.get());
        entries.accept(ThaumonBlocks.ARCANE_LANTERN.get());
        entries.accept(ThaumonBlocks.ARCANE_STONE_WINDOW.get());
        entries.accept(ThaumonBlocks.ARCANE_STONE_WINDOW_PANE.get());
        entries.accept(ThaumonBlocks.ARCANE_STONE_BUTTON.get());
        entries.accept(ThaumonBlocks.ARCANE_STONE_PRESSURE_PLATE.get());

        entries.accept(ThaumonBlocks.ELDRITCH_STONE.get());
        entries.accept(ThaumonBlocks.ELDRITCH_STONE_STAIRS.get());
        entries.accept(ThaumonBlocks.ELDRITCH_STONE_SLAB.get());
        entries.accept(ThaumonBlocks.ELDRITCH_STONE_WALL.get());
        entries.accept(ThaumonBlocks.ELDRITCH_STONE_BRICKS.get());
        entries.accept(ThaumonBlocks.ELDRITCH_STONE_BRICK_STAIRS.get());
        entries.accept(ThaumonBlocks.ELDRITCH_STONE_BRICK_SLAB.get());
        entries.accept(ThaumonBlocks.ELDRITCH_STONE_BRICK_WALL.get());
        entries.accept(ThaumonBlocks.ELDRITCH_STONE_TILES.get());
        entries.accept(ThaumonBlocks.ELDRITCH_STONE_TILE_STAIRS.get());
        entries.accept(ThaumonBlocks.ELDRITCH_STONE_TILE_SLAB.get());
        entries.accept(ThaumonBlocks.ELDRITCH_STONE_PILLAR.get());
        entries.accept(ThaumonBlocks.ELDRITCH_STONE_CAPSTONE.get());
        entries.accept(ThaumonBlocks.ELDRITCH_STONE_FACADE.get());
        entries.accept(ThaumonBlocks.CHISELED_ELDRITCH_STONE.get());
        entries.accept(ThaumonBlocks.CARVED_ELDRITCH_STONE.get());
        entries.accept(ThaumonBlocks.ENGRAVED_ELDRITCH_STONE.get());
        entries.accept(ThaumonBlocks.INLAID_ELDRITCH_STONE.get());
        entries.accept(ThaumonBlocks.ELDRITCH_LANTERN.get());
        entries.accept(ThaumonBlocks.ELDRITCH_STONE_WINDOW.get());
        entries.accept(ThaumonBlocks.ELDRITCH_STONE_WINDOW_PANE.get());

        entries.accept(ThaumonBlocks.ANCIENT_STONE.get());
        entries.accept(ThaumonBlocks.ANCIENT_STONE_STAIRS.get());
        entries.accept(ThaumonBlocks.ANCIENT_STONE_SLAB.get());
        entries.accept(ThaumonBlocks.ANCIENT_STONE_WALL.get());
        entries.accept(ThaumonBlocks.POLISHED_ANCIENT_STONE.get());
        entries.accept(ThaumonBlocks.POLISHED_ANCIENT_STONE_STAIRS.get());
        entries.accept(ThaumonBlocks.POLISHED_ANCIENT_STONE_SLAB.get());
        entries.accept(ThaumonBlocks.ANCIENT_STONE_BRICKS.get());
        entries.accept(ThaumonBlocks.ANCIENT_STONE_BRICK_STAIRS.get());
        entries.accept(ThaumonBlocks.ANCIENT_STONE_BRICK_SLAB.get());
        entries.accept(ThaumonBlocks.ANCIENT_STONE_BRICK_WALL.get());
        entries.accept(ThaumonBlocks.ANCIENT_STONE_TILES.get());
        entries.accept(ThaumonBlocks.ANCIENT_STONE_TILE_STAIRS.get());
        entries.accept(ThaumonBlocks.ANCIENT_STONE_TILE_SLAB.get());
        entries.accept(ThaumonBlocks.ANCIENT_STONE_DOOR.get());
        entries.accept(ThaumonBlocks.ANCIENT_STONE_PILLAR.get());
        entries.accept(ThaumonBlocks.ENGRAVED_ANCIENT_STONE.get());
        entries.accept(ThaumonBlocks.CHISELED_ANCIENT_STONE.get());
        entries.accept(ThaumonBlocks.RUNIC_ANCIENT_STONE.get());
        entries.accept(ThaumonBlocks.TILED_ANCIENT_STONE.get());
        entries.accept(ThaumonBlocks.INLAID_ANCIENT_STONE.get());
        entries.accept(ThaumonBlocks.ANCIENT_LANTERN.get());
        entries.accept(ThaumonBlocks.ANCIENT_STONE_WINDOW.get());
        entries.accept(ThaumonBlocks.ANCIENT_STONE_WINDOW_PANE.get());
        entries.accept(ThaumonBlocks.ANCIENT_STONE_BUTTON.get());
        entries.accept(ThaumonBlocks.ANCIENT_STONE_PRESSURE_PLATE.get());

        entries.accept(ThaumonBlocks.GREATWOOD_LEAVES.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_LEAVES.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_LEAF_POST.get());
        entries.accept(ThaumonBlocks.SILVERWOOD_LEAF_WALL.get());

        entries.accept(ThaumonBlocks.GRIMOIRE.get());
        entries.accept(ThaumonBlocks.GRIMOIRE_STACK.get());
        entries.accept(ThaumonBlocks.RESEARCH_NOTES.get());
        entries.accept(ThaumonBlocks.CRYSTAL_LAMP.get());
        entries.accept(ThaumonBlocks.RETORT.get());
        entries.accept(ThaumonBlocks.VIAL_RACK.get());
        entries.accept(ThaumonBlocks.CRYSTAL_STAND.get());

        entries.accept(ThaumonItems.MUTAGEN.get());
    }
}
